# Generated by Django 2.1 on 2018-09-12 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import repoApp.models.metricsRelated
import repoApp.models.testRelated


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidProject',
            fields=[
                ('project_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_build_tool', models.CharField(blank=True, default='gradle', max_length=16)),
                ('project_desc', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AppHasPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('app_location', models.CharField(max_length=512)),
                ('app_description', models.CharField(default=None, max_length=64, null=True)),
                ('app_version', models.FloatField(default=1)),
                ('app_flavor', models.CharField(default='', max_length=32)),
                ('app_build_type', models.CharField(blank=True, default='', max_length=16)),
                ('app_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_project', to='repoApp.AndroidProject')),
            ],
        ),
        migrations.CreateModel(
            name='AppMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_value', models.FloatField()),
                ('am_value_text', models.CharField(default='', max_length=32)),
                ('am_coeficient', models.IntegerField(default=1)),
                ('am_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('am_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aapp', to='repoApp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=32)),
                ('class_package', models.CharField(max_length=32)),
                ('class_non_acc_mod', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('class_acc_modifier', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('class_superclass', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('class_is_interface', models.BooleanField(default=False)),
                ('class_implemented_ifaces', models.CharField(blank=True, default='', max_length=256)),
                ('class_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_app', to='repoApp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_value', models.FloatField()),
                ('cm_value_text', models.CharField(default='', max_length=32)),
                ('cm_coeficient', models.IntegerField(default=1)),
                ('cm_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmetric', to='repoApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('device_brand', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('device_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_state_mem', models.IntegerField()),
                ('device_state_cpu_free', models.IntegerField()),
                ('device_state_nr_processes_running', models.IntegerField()),
                ('device_state_api_level', models.IntegerField()),
                ('device_state_android_version', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportClass',
            fields=[
                ('import_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('import_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classofimport', to='repoApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('method_id', models.CharField(max_length=384, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=256)),
                ('method_non_acc_mod', models.CharField(blank=True, default='', max_length=32)),
                ('method_acc_modifier', models.CharField(blank=True, default='', max_length=16)),
                ('method_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classofmethod', to='repoApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='MethodInvoked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='repoApp.Method')),
            ],
        ),
        migrations.CreateModel(
            name='MethodMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_value', models.FloatField()),
                ('mm_value_text', models.CharField(default='', max_length=32)),
                ('mm_coeficient', models.IntegerField(default=1)),
                ('mm_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mm_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmmethod', to='repoApp.Method')),
                ('mm_method_invoked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmmethodHasMetric', to='repoApp.MethodInvoked')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('metric_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('metric_type', enumfields.fields.EnumField(enum=repoApp.models.metricsRelated.MetricType, max_length=1)),
                ('metric_category', enumfields.fields.EnumField(default='o', enum=repoApp.models.metricsRelated.MetricCategory, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('profiler_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('profiler_type', enumfields.fields.EnumField(enum=repoApp.models.testRelated.ProfilerType, max_length=1)),
                ('profiler_version', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('study_authors', models.CharField(max_length=128)),
                ('study_publisher', models.CharField(max_length=64)),
                ('study_year', models.IntegerField()),
                ('study_isbn', models.CharField(max_length=64)),
                ('study_organization', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_app', to='repoApp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('value_text', models.CharField(default='', max_length=32)),
                ('coeficient', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='repoApp.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrientation',
            fields=[
                ('test_orientation_designation', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('test_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_results_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_results_seed', models.IntegerField()),
                ('test_results_description', models.CharField(max_length=100)),
                ('test_results_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testedOn', to='repoApp.Device')),
                ('test_results_device_begin_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begin_state', to='repoApp.DeviceState')),
                ('test_results_device_end_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_state', to='repoApp.DeviceState')),
                ('test_results_profiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiledOn', to='repoApp.Profiler')),
                ('test_results_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='repoApp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='testmetric',
            name='test_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='repoApp.TestResults'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type', to='repoApp.TestOrientation'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_tool', to='repoApp.Tool'),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_related_study',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accordingto', to='repoApp.Study'),
        ),
        migrations.AddField(
            model_name='methodmetric',
            name='mm_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmmethodHasMetric', to='repoApp.Metric'),
        ),
        migrations.AddField(
            model_name='methodinvoked',
            name='test_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='repoApp.TestResults'),
        ),
        migrations.AddField(
            model_name='classmetric',
            name='cm_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasMetric', to='repoApp.Metric'),
        ),
        migrations.AddField(
            model_name='appmetric',
            name='am_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahasMetric', to='repoApp.Metric'),
        ),
        migrations.AddField(
            model_name='apphaspermission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasapp', to='repoApp.Application'),
        ),
        migrations.AddField(
            model_name='apphaspermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haspermission', to='repoApp.AppPermission'),
        ),
        migrations.AlterUniqueTogether(
            name='testmetric',
            unique_together={('test_results', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('test_application', 'test_tool', 'test_orientation')},
        ),
        migrations.AlterUniqueTogether(
            name='methodmetric',
            unique_together={('mm_method', 'mm_metric', 'mm_timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='methodinvoked',
            unique_together={('method', 'test_results')},
        ),
        migrations.AlterUniqueTogether(
            name='method',
            unique_together={('method_name', 'method_class', 'method_id')},
        ),
        migrations.AlterUniqueTogether(
            name='importclass',
            unique_together={('import_name', 'import_class')},
        ),
        migrations.AlterUniqueTogether(
            name='classmetric',
            unique_together={('cm_class', 'cm_timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='appmetric',
            unique_together={('am_app', 'am_metric', 'am_timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='apphaspermission',
            unique_together={('application', 'permission')},
        ),
    ]
