# Generated by Django 2.0.4 on 2018-04-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric_id',
            new_name='metric_name',
        ),
    ]
