# Generated by Django 2.0.4 on 2018-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0002_auto_20180430_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmetric',
            name='am_unit',
        ),
        migrations.RemoveField(
            model_name='methodmetric',
            name='mm_unit',
        ),
        migrations.RemoveField(
            model_name='testmetric',
            name='unit',
        ),
        migrations.AddField(
            model_name='appmetric',
            name='am_coeficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='methodmetric',
            name='mm_coeficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testmetric',
            name='coeficient',
            field=models.IntegerField(default=1),
        ),
    ]
