# Generated by Django 2.0.4 on 2018-05-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0003_auto_20180430_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodmetric',
            name='mm_method_invoked',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmmethodHasMetric', to='repoApp.MethodInvoked'),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_results_device_begin_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begin_state', to='repoApp.DeviceState'),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_results_device_end_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_state', to='repoApp.DeviceState'),
        ),
    ]
