# Generated by Django 2.0.4 on 2018-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0004_auto_20180501_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_location',
            field=models.CharField(max_length=512),
        ),
    ]
