# Generated by Django 2.0.4 on 2018-05-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoApp', '0005_auto_20180503_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
